# python scripts/eval/benchmark_recon.py -cn benchmark_tapecam_mirflickr
defaults:
  - benchmark
  - _self_

dataset: HFDataset
batchsize: 4
device: "cuda:0"

huggingface:
  repo: "bezzam/TapeCam-Mirflickr-25K"
  cache_dir: /dev/shm
  psf: psf.png
  image_res: [900, 1200]  # used during measurement
  rotate: False   # if measurement is upside-down
  flipud: False
  flip_lensed: False   # if rotate or flipud is True, apply to lensed
  alignment:
    top_left: [45, 95]  # height, width
    height: 250
  downsample: 1
  single_channel_psf: False

## -- reconstructions trained with same dataset/system
algorithms: [
  "ADMM",

  # -- reconstructions trained on measured data
  "hf:tapecam:mirflickr:U5+Unet8M",
  "hf:tapecam:mirflickr:TrainInv+Unet8M",
  "hf:tapecam:mirflickr:MMCN4M+Unet4M",
  "hf:tapecam:mirflickr:Unet4M+U5+Unet4M",
  "hf:tapecam:mirflickr:Unet4M+TrainInv+Unet4M",
  "hf:tapecam:mirflickr:Unet2M+MMCN+Unet2M",
  "hf:tapecam:mirflickr:Unet4M+U10+Unet4M",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_flips_rotate10",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_aux1",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_flips",
  # "hf:tapecam:mirflickr:Unet4M+U5+Unet4M_flips_rotate10",

  # # below models need `single_channel_psf = True`
  # "hf:tapecam:mirflickr:MWDN8M",    
  # "hf:tapecam:mirflickr:Unet2M+MWDN6M",

  # ## -- reconstructions trained on other datasets/systems
  # "hf:diffusercam:mirflickr:Unet4M+U10+Unet4M",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U5+Unet4M_wave",
  # "hf:digicam:celeba_26k:Unet4M+U5+Unet4M_wave",
  # "hf:digicam:mirflickr_single_25k:Unet4M+U10+Unet4M_wave",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_tapecam",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_tapecam_post",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_tapecam_pre",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_digicam_multi_post",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_ft_tapecam",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_ft_tapecam_post",
  # "hf:diffusercam:mirflickr:Unet4M+U5+Unet4M_ft_tapecam_pre",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_digicam_multi_pre",
  # "hf:diffusercam:mirflickr_sim:Unet4M+U5+Unet4M_ft_digicam_multi",
]

save_idx: [1, 2, 4, 5, 9]
n_iter_range: [100]    # for ADM
