# fine-tune mask for PSF, but don't re-simulate
# python scripts/recon/train_unrolled.py -cn train_celeba_digicam_mask
defaults:
  - train_celeba_digicam
  - _self_

# Train Dataset
files:
  # dataset: /scratch/bezzam/celeba_adafruit_random_2mm_20230720_10K
  # psf: data/psf/adafruit_random_2mm_20231907.png
  # vertical_shift: null
  # horizontal_shift: null
  # crop: null

  downsample: 2
  dataset: /scratch/bezzam/celeba/celeba_adafruit_random_30cm_2mm_20231004_26K
  psf: rpi_hq_adafruit_psf_2mm/raw_data_rgb.png
  vertical_shift: -117
  horizontal_shift: -25
  crop:
    vertical: [0, 525]
    horizontal: [265, 695]

  celeba_root: /scratch/bezzam
  

# for prepping ground truth data
simulation:
  scene2mask: 0.25   # [m]
  mask2sensor: 0.002   # [m]
  object_height: 0.33   # [m]
  snr_db: null
  downsample: null
  random_vflip: False
  random_hflip: False
  quantize: False


reconstruction:
  method: unrolled_admm
  unrolled_admm:
    # Number of iterations
    n_iter: 10

  pre_process: 
    network : null  # UnetRes or DruNet or null
    depth : 2 # depth of each up/downsampling layer. Ignore if network is DruNet
  post_process: 
    network : null  # UnetRes or DruNet or null
    depth : 2 # depth of each up/downsampling layer. Ignore if network is DruNet

#Training
training:
  batch_size: 2
  epoch: 25
  eval_batch_size: 15
  crop_preloss: True

  save_every: 5

#Trainable Mask
trainable_mask:
  mask_type: AdafruitLCD #Null or "TrainablePSF" or "AdafruitLCD"
  # "random" (with shape of config.files.psf) or path to npy file 
  grayscale: False
  mask_lr: 1e-3
  L1_strength: False

  # for fine-tuning mask values
  train_mask_vals: True
  train_color_filter: True

  # -- only for AdafruitLCD
  # initial_value: data/psf/adafruit_random_pattern_20230719.npy
  # ap_center: [59, 76]
  # ap_shape: [19, 26]
  # rotate: -0.8   # rotation in degrees
  # vertical_shift: -20 # [px]
  # horizontal_shift: -100  # [px]


  initial_value: /home/bezzam/LenslessPiCam/adafruit_random_pattern_20231004_174047.npy  
  ap_center: [58, 76]
  ap_shape: [19, 25]
  rotate: 0   # rotation in degrees
  # to align with measured PSF (so reconstruction also aligned)
  vertical_shift: -80 # [px]
  horizontal_shift: -60  # [px]
  
  slm: adafruit
  sensor: rpi_hq
  flipud: True
  waveprop: False
  
  # below are ignored if waveprop=False
  scene2mask: 0.3   # [m]
  mask2sensor: 0.002   # [m]
  